### ISSUE TITLE
historical promise not returning structured data

### ISSUE THREAD

**Issue by sunilgautam** [zerodhatech/kiteconnectjs#11]
historical promise returning unstructured data like
`[ '2017-06-06T09:15:00+0530', 965.7, 973, 964.65, 973, 112886 ]`
instead of
`
[
  {
    date: '2015-02-10T00:00:00+0530',
    open: 277.5,
    high: 290.8,
    low: 275.7,
    close: 287.3,
    volume: 22589681
  }
]
`

After looking into source code i noticed that [this condition](https://github.com/rainmattertech/kiteconnectjs/blob/master/lib/index.js#L589) should be `response.statusCode`.

**Comment by vividvilla** [comment]
That seems to be an issue. Will release a patch in next version.
