### ISSUE TITLE
JS heap out of memory

### ISSUE THREAD

**Issue by asbalaji** [zerodhatech/kiteconnectjs#12]
Hi
I hit the following error when kite.orders() statement is executed.

<--- Last few GCs --->

   31665 ms: Mark-sweep 1386.9 (1442.5) -> 1386.9 (1442.5) MB, 904.2 / 0.0 ms [allocation failure] [GC in old space requested].
   32591 ms: Mark-sweep 1386.9 (1442.5) -> 1386.9 (1421.5) MB, 926.6 / 0.0 ms [last resort gc].
   33492 ms: Mark-sweep 1386.9 (1421.5) -> 1386.9 (1421.5) MB, 900.4 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000023D67BCFB61 <JS Object>
    2: encode(aka encode) [D:\Balaji\stock\node_modules\request\node_modules\qs\lib\utils.js:~118] [pc=0000003A658E9E00] (this=0000023D67B04381 <undefined>,str=0000022E800A7901 <Very long string[7279]>)
    3: arguments adaptor frame: 2->1
    4: stringify(aka stringify) [D:\Balaji\stock\node_modules\request\node_modules\qs\lib\stringify.js:~32] [pc=0000003A658EB680] (this=0000023D67B04381 <u...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

I use nodeJS version v6.9.5 on Windows 10. Is there any specific version of nodeJS that you want me to use?
I have successful authentication to zerodha platform, have valid api_key, api_secret, access_token.

This is almost a showstopper to me.
Could you please help me identifying the problem?

Thanks
Balaji

**Comment by vividvilla** [comment]
I have test this on node v6.11.5 on Windows and  node 6.1.0 on MacOS and both seems to be working without any issues. Can you provide more details on the issue like how big is your orderbook response?

**Comment by asbalaji** [comment]
My orderbook is empty. Yesterday was my first day on kiteconnectjs. After going through successful login, I wanted to place an order. My logic is to go through the list of open orders and avoid them getting placed again. In order to do that, First I was trying to fetch the list of orders where it failed miserably.

**Comment by vividvilla** [comment]
I did test for empty orderbook also and it gave me the response. It will be helpful to debug if you share your code here.

```
C:\Users\Zero\Documents>node kiteconnect-test.js
{ status: 'success', data: [] }
```

**Comment by asbalaji** [comment]
I think I found the issue. Steps to reproduce.
1) Login to zerodha.
2) Get request token by sending get request to https://kite.trade/connect/login?api_key=xxx
3) Wait for 2-3 mins(till request_token expires)
4) Get access_token using kite.requestAccessToken()
5) Initialize kite with this access_token
6) Now issue kite.orders(). 
7) Bang. JS heap goes out of memory.

I was having few pattern recognizing code running in between steps 2 & 3. After removing them I got this working.

Please try these steps and let me know if you are able to reproduce.

**Comment by vividvilla** [comment]
If `request_token` is expired then you will get error while calling `kite.requestAccessToken()` and if you call `kite.orders` without retrieving `acceess_token` then you will again get 400 error..
```
{ status: 'error',
  message: 'Invalid session credentials',
  error_type: 'TokenException' }
```

Also request_token expires 5 mins after it is generated.
