### ISSUE TITLE
Support for Quote and OHLC calls

### ISSUE THREAD

**Issue by pratikgaloria** [zerodhatech/kiteconnectjs#15]
Can we please have support for `quote/ohcl` and `quote/ltp` calls for bulk quotes? I am ready to help here.

**Comment by vividvilla** [comment]
Its been added in upcoming release which you can find it on - https://github.com/zerodhatech/kiteconnectjs/tree/kite3

Since this is in beta there can be other changes to before it gets released.

**Comment by pratikgaloria** [comment]
The data receiving from websocket is too fast, can we put a delay or define somewhere that we want to read ticks every 2 seconds for example?

**Comment by vividvilla** [comment]
You can do this in `on_tick` callback but if you are pulling data for few instruments with interval of few seconds then you can go with new bulk `quote` call.

**Comment by pratikgaloria** [comment]
New bulk quote call seems not be designed actually for list of arguments.

It is coded
`_get("market.quote.ohlc", {"i", instruments})`

but it works only for one instrument. How to pass list of instruments? `NSE:INFY, NSE:RELIANCE` is not working and also could sense that it was not coded to achieve in bulk.

**Comment by vividvilla** [comment]
@pratikgaloria You can send array of instruments like this

    k.getQuote(["NSE:INFY", "NSE:RELIANCE"]);
