### ISSUE TITLE
#kite3: requestAccessToken method in KiteConnect seems to be missing. 

### ISSUE THREAD

**Issue by ffiw** [zerodhatech/kiteconnectjs#17]
Readme says use requestAccessToken to generate access token but this method is not at all found in connect.js file. How do I generate access token ?

**Comment by ffiw** [comment]
Please update readme to use generateSession to fetch access token.

**Comment by vividvilla** [comment]
Thanks for reporting, its been updated in recent commit - 30339597c0bfe2d3dcddf0d53e27300103593e56
