### ISSUE TITLE
#kite3: Instrument token ids returned by your instrument api and token ids inside ticks don't match.

### ISSUE THREAD

**Issue by ffiw** [zerodhatech/kiteconnectjs#18]
Instrument token ids returned by your instrument api and token ids inside ticks are different. 

I don't know whether it's a bug with the js libarary or on your server side. 

For example:
TCS:NSE EQ token id is 2953217 according to instrument API call.
But the token id inside tick data is 11536
TCS:
[ { tradable: true,
    mode: 'quote',
    instrument_token: 11536,
    last_price: 3102,
    last_quantity: 10,
    average_price: 3112.02,
    volume: 1619805,
    buy_quantity: 4858,
    sell_quantity: 0,
    ohlc: { open: 3114.95, high: 3142.35, low: 3090.05, close: 3116.4 },
    change: -0.4620716211012736 } ]

**Comment by ffiw** [comment]
In older version token is extracted from websocket data using these lines.

var t = buf2long(bin.slice(0, 4)),
				token = t >> 8,
				segment = t & 0xff;

in newer version you are not doing bit shift thing.
https://github.com/zerodhatech/kiteconnectjs/blob/fc6c2e449cdf42bec0be915bbc506add259bfc06/lib/ticker.js#L500

**Comment by ffiw** [comment]
Instrument API returns this data for TCS:NSE

{ instrument_token: '2953217',
  exchange_token: '11536',
  tradingsymbol: 'TCS',
  name: 'TATA CONSULTANCY SERV LT',
  last_price: '0.0',
  expiry: '',
  strike: '0.0',
  tick_size: '0.05',
  lot_size: '1',
  instrument_type: 'EQ',
  segment: 'NSE',
  exchange: 'NSE' }


Websocket is getting 11536 (exchange id) instead of instrument token id. Clearly seems to be server side issue.

**Comment by vividvilla** [comment]
@ffiw This has already been fixed in this commit 875c6e0e33901626fd76856c2d53b9b84450b20d 

Please reinstall package via NPM

`npm install kiteconnect@beta`
